### ISSUE TITLE
double single-quote `'` (used to escape `'` in psql) within HERDOC crashes parser

### ISSUE THREAD

**Issue by btihen** [whitesmith/rubycritic#520]
Using
- Rails 8.0 
- ruby 3.2.2
- rubycritic 4.9.2

HERDOC that crashes parser:
```ruby
sql = <<SQL.squish
  insert into public.pendenz_templates
  ("bezeichnung_de","bezeichnung_fr","bezeichnung_it","bezeichnung_en","pendenz_kategorie_cd",
    "pendenz_subject_de","pendenz_subject_fr","pendenz_subject_it","pendenz_subject_en","lock_version",
    "created_at","updated_at","pendenz_rolle_id","aktiv","referenz","manuell_loeschbar","sammel_pendenz","pendenz_typ","verwaltungszeitraum_beachten","zeitliche_abhaengigkeit","number_of_days")
  select 'Auflösung Sicherheitsleistung','Résolution du dépôt de garantie','Risoluzione deposito cauzionale','Auflösung Sicherheitsleistung','03',
    'Auflösung Sicherheitsleistung','Résolution du dépôt de garantie','Résolution du dépôt de garantie','Auflösung Sicherheitsleistung',0,
    now(), now(),1,'0','aufloesung_sicherheitsleistung','0','0','individuell','0','1',-90
  where not exists(select *
            from public.pendenz_templates pt
            where pt.referenz = 'aufloesung_sicherheitsleistung');

  insert into public.ruby_scripts
  ("id","bezeichnung_de","bezeichnung_fr","bezeichnung_it","bezeichnung_en","script","aktiv","cron","lock_version","created_at","updated_at","authorization_roles","referenz")
  select 88,'Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren',
  'user = User.find_by username: ''admind''
  options[''user_id''] = User.find_by(username: ''admind'').id','1','15 5 * * *',1,'2023-04-14 10:25:01.5092760','2023-04-14 10:35:18.8235140','["admin"]','datenbasierte_pendenzen_generieren'
  where not exists(select *
            from public.ruby_scripts rs
            where rs.id = 88);
SQL
    execute(sql)
  end
```

Error:
```
running flay smells
...
running flog smells
...
running reek smells
...
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:110:in `rescue in wrap_exceptions': Source 'db/migrate/20230427122344_create_help_table_for_pendenzen.rb' cannot be processed by Reek due to a syntax error in the source file. (Reek::Errors::SyntaxError)
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:103:in `wrap_exceptions'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:93:in `run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:61:in `smells'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers/smells/reek.rb:30:in `add_smells_to'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers/smells/reek.rb:17:in `block in run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers/smells/reek.rb:16:in `run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers_runner.rb:32:in `block in run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers_runner.rb:29:in `each'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers_runner.rb:29:in `run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/commands/default.rb:24:in `critique'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/commands/default.rb:19:in `execute'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/cli/application.rb:21:in `execute'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/bin/rubycritic:10:in `<top (required)>'
	from .gems/bin/rubycritic:25:in `load'
	from .gems/bin/rubycritic:25:in `<main>'
/builds/garaio-rem/grem/garaio-rem-core/.gems/gems/parser-3.3.7.4/lib/parser/diagnostic/engine.rb:72:in `process': unexpected token tIDENTIFIER (Parser::SyntaxError)
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/parser-3.3.7.4/lib/parser/base.rb:286:in `on_error'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/racc-1.8.1/lib/racc/parser.rb:263:in `_racc_do_parse_c'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/racc-1.8.1/lib/racc/parser.rb:263:in `do_parse'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/parser-3.3.7.4/lib/parser/base.rb:190:in `parse'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/parser-3.3.7.4/lib/parser/base.rb:207:in `parse_with_comments'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/source/source_code.rb:117:in `parse'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/source/source_code.rb:53:in `syntax_tree'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:116:in `syntax_tree'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:120:in `examine_tree'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:94:in `block in run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:104:in `wrap_exceptions'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:93:in `run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/reek-6.4.0/lib/reek/examiner.rb:61:in `smells'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers/smells/reek.rb:30:in `add_smells_to'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers/smells/reek.rb:17:in `block in run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers/smells/reek.rb:16:in `run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers_runner.rb:32:in `block in run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers_runner.rb:29:in `each'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/analysers_runner.rb:29:in `run'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/commands/default.rb:24:in `critique'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/commands/default.rb:19:in `execute'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/lib/rubycritic/cli/application.rb:21:in `execute'
	from /builds/garaio-rem/grem/garaio-rem-core/.gems/gems/rubycritic-4.9.2/bin/rubycritic:10:in `<top (required)>'
	from .gems/bin/rubycritic:25:in `load'
	from .gems/bin/rubycritic:25:in `<main>'
```

The error isn't very clear as to the cause, but once identified I was also able to rewrite the code - so there is a work around.  So hopefully, if the problem is not worth fixing this issue will help others with the work around

**work around ** - rewrite code without psql escapes then run the string through `quoted_script = ActiveRecord::Base.connection.quote(script)` and then insert the string into SQL query.
```
    script = <<~RUBY
      user = User.find_by(username: 'admind')
      options['user_id'] = User.find_by(username: 'admind').id
    RUBY
    quoted_script = ActiveRecord::Base.connection.quote(script)

    sql = <<SQL.squish
  insert into public.ruby_scripts
("id","bezeichnung_de","bezeichnung_fr","bezeichnung_it","bezeichnung_en","script","aktiv","cron","lock_version","created_at","updated_at","authorization_roles","referenz")
  select 88,'Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren',
  #{quoted_script},'1','15 5 * * *',1,'2023-04-14 10:25:01.5092760','2023-04-14 10:35:18.8235140','["admin"]','datenbasierte_pendenzen_generieren'
  where not exists(select *
            from public.ruby_scripts rs
            where rs.id = 88);
SQL
    execute(sql)
```

**Comment by faisal** [comment]
This failure appears to come out of Reek:

``` shell
$ reek -v                  
reek 6.4.0
$ cat foo.rb 
sql = <<SQL.squish
  insert into public.ruby_scripts
("id","bezeichnung_de","bezeichnung_fr","bezeichnung_it","bezeichnung_en","script","aktiv","cron","lock_version","created_at","updated_at","authorization_roles","referenz")
  select 88,'Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren','Datenbasierte Pendenzen generieren',
  'user = User.find_by username: ''admind''
  options[''user_id''] = User.find_by(username: ''admind'').id','1','15 5 * * *',1,'2023-04-14 10:25:01.5092760','2023-04-14 10:35:18.8235140','["admin"]','datenbasierte_pendenzen_generieren'
  where not exists(select *
            from public.ruby_scripts rs
            where rs.id = 88);
SQL
    execute(sql)
  end
$ reek foo.rb 
Inspecting 1 file(s):
        !!!
        Source 'foo.rb' cannot be processed by Reek due to a syntax error in the source file.

        This is a problem that is outside of Reek's scope and should be fixed by you, the
        user, in order for Reek being able to continue.

        Things you can try:
        - Check the syntax of the problematic file
        - If the file is not in fact a Ruby file, exclude it in your .reek.yml file

        Exception message:

        #<Parser::SyntaxError: unexpected token kEND>

        Original backtrace:

        /Users/faisal/.gem/ruby/3.4.3/gems/parser-3.3.8.0/lib/parser/diagnostic/engine.rb:72:in 'Parser::Diagnostic::Engine#process'
	/Users/faisal/.gem/ruby/3.4.3/gems/parser-3.3.8.0/lib/parser/base.rb:289:in 'Parser::Base#on_error'
	/Users/faisal/.gem/ruby/3.4.3/gems/racc-1.8.1/lib/racc/parser.rb:263:in 'Racc::Parser#_racc_do_parse_c'
	/Users/faisal/.gem/ruby/3.4.3/gems/racc-1.8.1/lib/racc/parser.rb:263:in 'Racc::Parser#do_parse'
	/Users/faisal/.gem/ruby/3.4.3/gems/parser-3.3.8.0/lib/parser/base.rb:193:in 'Parser::Base#parse'
	/Users/faisal/.gem/ruby/3.4.3/gems/parser-3.3.8.0/lib/parser/base.rb:210:in 'Parser::Base#parse_with_comments'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/source/source_code.rb:117:in 'Reek::Source::SourceCode#parse'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/source/source_code.rb:53:in 'Reek::Source::SourceCode#syntax_tree'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/examiner.rb:116:in 'Reek::Examiner#syntax_tree'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/examiner.rb:120:in 'Reek::Examiner#examine_tree'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/examiner.rb:94:in 'block in Reek::Examiner#run'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/examiner.rb:104:in 'Reek::Examiner#wrap_exceptions'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/examiner.rb:93:in 'Reek::Examiner#run'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/examiner.rb:61:in 'Reek::Examiner#smells'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/examiner.rb:77:in 'Reek::Examiner#smelly?'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/report/progress_formatter.rb:43:in 'Reek::Report::ProgressFormatter::Dots#progress'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/report/text_report.rb:22:in 'Reek::Report::TextReport#add_examiner'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/cli/command/report_command.rb:26:in 'block in Reek::CLI::Command::ReportCommand#populate_reporter_with_smells'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/cli/command/report_command.rb:25:in 'Array#each'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/cli/command/report_command.rb:25:in 'Reek::CLI::Command::ReportCommand#populate_reporter_with_smells'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/cli/command/report_command.rb:17:in 'Reek::CLI::Command::ReportCommand#execute'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/lib/reek/cli/application.rb:32:in 'Reek::CLI::Application#execute'
	/Users/faisal/.gem/ruby/3.4.3/gems/reek-6.4.0/bin/reek:12:in '<top (required)>'
	/Users/faisal/.gem/ruby/3.4.3/bin/reek:25:in 'Kernel#load'
	/Users/faisal/.gem/ruby/3.4.3/bin/reek:25:in '<main>'

        !!!
.

$ 
```

I could also reproduce this against Reek 6.5.0.

I think this is worth filing at https://github.com/troessner/reek/issues.

**Comment by MarcusAl** [comment]
Tried to repro this with the exact HEREDOC against current versions and it parses cleanly all the way through:

- `ruby -c` → Syntax OK
- `parser` gem 3.3.11.1 → AST returns fine
- `reek` 6.5.0 → 0 warnings, exit 0
- `rubycritic` 5.0.0 → full pipeline succeeds (score 99.44)

Looks like it was fixed somewhere upstream between 6.4.0 and 6.5.0. Probably safe to close.

**Comment by etagwerker** [comment]
@MarcusAl Thanks for checking! 👍🏻

**Comment by faisal** [comment]
I still see this problem, but it's in Reek rather than Rubycritic.
